resources:
  - ../base
  - namespace.yaml      # ensure namespace is created by kustomize

namespace: kustomapp

patchesStrategicMerge:
  - replicas.yaml

configMapGenerator:
  - name: app-config
    files:
      - config.properties


